const tapas = [
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
    {
        id: 1,
        name: "Patatas bravas",
        price: "6.25€",
        image: "img/patatas-bravas.jpg",
    },
    {
        id: 2,
        name: "Croquetas de jamón",
        price: "5,00€",
        image: "img/croquetas-jamon.jpg",
    },
];